Feat/ertb keyword tracking
Kodnot/ToNote pull request #10
Opened 2019-03-09 01:16 UTC by t-eliks

Set up keyword tracking for ExtendedRichTextBox control. Allows / commands, ex. /todo.

2019-03-09 17:54 UTC, t-eliks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add base TODO items](https://trello.com/c/FmMgIkNN/11-add-base-todo-items)

2019-03-09 18:00 UTC, t-eliks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow inserting TODOs anywhere](https://trello.com/c/cGs43i1W/13-allow-inserting-todos-anywhere)

2019-03-09 18:02 UTC, t-eliks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add an ability to insert a TODO item without clicking the button](https://trello.com/c/F1GddRqj/28-add-an-ability-to-insert-a-todo-item-without-clicking-the-button)

2019-03-09 21:13 UTC, Kodnot requested changes

2019-03-09 21:13 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +                if (this.IsLoaded)
Invert if to reduce nesting

2019-03-09 21:13 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +                            if (keyword == keywordaction.Keyword)
camelCase, `keywordaction` -> `keywordAction`

2019-03-09 21:13 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +                            if (keyword != keywordaction.Keyword + ' ') return;
Also add newline as a possible suffix of the keyword. Typing "/note" + enter feels natural, but currently does not work.

2019-03-09 21:13 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +                    if (lastChar == '/' && secondToLastChar == ' ')
Should also work when the second to last char is new line (when the keyword is entered at the start of a new line). Currently this works only sometimes. If you create a new RTB and enter "/note ", the keyword will trigger properly. However, if you create a new RTB, press enter and then type "/note ", the keyword will not trigger.

2019-03-09 21:13 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +            var keywordaction = new KeywordAction() { Keyword = keyword, Action = action };
[Nitpick] `keywordaction` -> `keywordAction`

2019-03-09 21:13 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +            if (!_trackedKeywords.Contains(keywordaction))
I think this check is redundant. `KeywordAction` contains an `Action`. For a comparison between two `KeywordAction` instances to return true, they would have to reference the same action (default reference equality comparison). One would have to go out of their way to trigger this check, for example even just copy-paste duplicating the "note" keyword registering code does not trigger this condition.
If you think that one shoud only be able to register one action per keyword, overload the equality comparison operators for `KeywordAction`. 
However, I don't really see why you shouldn't be able to register multiple actions per keyword (unless maybe there could be some issues with execution order?). If we allow this, you can just remove this check, but then also don't forget to remove `return` from the foreach where you search for maching keywords.

2019-03-10 17:34 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +                        return;
Remove this return, as you currently allow registering multiple keywords per action, but only execute the first found action.

2019-03-10 17:58 UTC, Kodnot approved these changes

2019-03-10 18:09 UTC, merged