Added TextBlockStyles and refurbished AboutPage
Kodnot/ToNote pull request #22
Opened 2019-03-12 22:33 UTC by Hofkee

2019-03-12 22:36 UTC, Hofkee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a base textblock style](https://trello.com/c/QFf1wfkd/52-create-a-base-textblock-style)

2019-03-13 11:39 UTC, t-eliks commented on ToNote/Views/AboutPageView.xaml
> +            <TextBlock Text="Version" FontSize="14" Margin="15,-40,0,0" Foreground="#404040"/>
Dark foreground on dark background

2019-03-13 11:39 UTC, t-eliks commented on ToNote/Views/AboutPageView.xaml
> +            <TextBlock Text="Developers" Grid.Row="1" VerticalAlignment="Bottom" Margin="20,0,20,85" FontSize="14" Foreground="#404040" />
Also here

2019-03-13 18:43 UTC, Hofkee commented on ToNote/Views/AboutPageView.xaml
> +            <TextBlock Text="Version" FontSize="14" Margin="15,-40,0,0" Foreground="#404040"/>
IMO it looks fine

2019-03-13 21:22 UTC, Kodnot commented
1. Make the "ToNote for Windows" centered.
1. Move "Developers" Section higher. It should go directly after "Version". The "2019 Team Sugma" should be moved to the bottom, it should be like a footer (and should be spelled like I spelt it here, with a space and without a dot at the end. Add a copyright sign for bonus points)
1. Fix indentation. Now Developers are centered, while Version is stuck to the left. Probably remove indentation and centering from the development section.
1. Remove dots after developer list

2019-03-13 21:27 UTC, Kodnot requested changes
1. Make the "ToNote for Windows" centered.
1. Move "Developers" Section higher. It should go directly after "Version". The "2019 Team Sugma" should be moved to the bottom, it should be like a footer (and should be spelled like I spelt it here, with a space and without a dot at the end. Add a copyright sign for bonus points)
1. Fix indentation. Now Developers are centered, while Version is stuck to the left. Probably remove indentation and centering from the development section.
1. Remove dots after developer list

2019-03-19 22:07 UTC, Kodnot approved these changes

2019-03-19 22:08 UTC, Kodnot submitted a review, later dismissed
The developer list is still sliiightly indented. Also, the window breaks if resized. @t-eliks , would it be difficult to lock the about page size so that it cannot be resized?

2019-03-19 22:13 UTC, t-eliks commented
> The developer list is still sliiightly indented. Also, the window breaks if resized. @t-eliks , would it be difficult to lock the about page size so that it cannot be resized?

Need to add a boolean property to BaseDialogViewModel and bind ResizeMode with a converter to it. Shouldn't use the ResizeMode enumerator to uphold the philosophy of ViewModel doesn't know anything about the View.

2019-03-20 13:46 UTC, Hofkee commented
Visur marginai sudeti po 15 is kaires nezinau kodel atrodo, kad siek tiek iseje

2019-03-21 12:30 UTC, Kodnot approved these changes

2019-03-21 12:30 UTC, merged