Feat/text box split on todo insertion
Kodnot/ToNote pull request #30
Opened 2019-03-20 10:58 UTC by t-eliks

Add textbox split after /todo command

2019-03-22 20:26 UTC, t-eliks commented
![](https://github.trello.services/images/mini-trello-icon.png) [As a user, I want to insert a TODO in the middle of a note so that I don't have to split a note manually](https://trello.com/c/cGs43i1W/13-as-a-user-i-want-to-insert-a-todo-in-the-middle-of-a-note-so-that-i-dont-have-to-split-a-note-manually)

2019-03-25 09:29 UTC, Kodnot requested changes

2019-03-25 09:29 UTC, Kodnot commented on ToNote/Controls/ExtendedRichTextBox.cs
> +                    if (lastChar == '/' && secondToLastChar == ' ' || secondToLastChar == '\n')
You need () for the || condition here

2019-03-25 09:29 UTC, Kodnot commented on ToNote/Controls/NotePanel.cs
> +            extendedTextBoxControl.TrackKeyword("n", () => {
Testing leftovers, revert this back to "note"

2019-03-26 12:14 UTC, Kodnot approved these changes

2019-03-26 13:37 UTC, merged