Tags expander
Kodnot/ToNote pull request #43
Opened 2019-04-12 15:33 UTC by Hofkee

Made TagsExpander to look smoother. (There is some bullshit in expander.header, because yet don't know how to make bindable text)

2019-04-12 18:35 UTC, t-eliks requested changes

2019-04-12 18:35 UTC, t-eliks commented on ToNote/UI/ExpanderStyles.xaml
> +                            <TextBlock x:Name="text" Text="Tags" Grid.Column="2" Foreground="{StaticResource DefaultToggleButtonForegroundBrush}" FontSize="12"/>
Remove this line. The header content should be passed to the Expander through Header attribute. The Content Presenter thats is on line 20 displays it automagically.

2019-04-12 18:35 UTC, t-eliks commented on ToNote/UI/ExpanderStyles.xaml
> +                            <Setter Property="Foreground" TargetName="text" Value="{StaticResource DefaultExpanderMouseOverBrush}"/>
The header of the expander should not be affected by triggers, considering it can be anything, not just plain text. Remove this from all triggers.

2019-04-12 18:35 UTC, t-eliks commented on ToNote/UI/ExpanderStyles.xaml
> +                            <Setter Property="Stroke" TargetName="arrow" Value="{StaticResource DefaultExpanderMouseOverBrush}"/>
The alternate color should not be this dark, doesn't look good when the background of the app is also dark.

2019-04-12 18:35 UTC, t-eliks commented on ToNote/UI/ExpanderStyles.xaml
> +                            <Path x:Name="arrow" RenderTransformOrigin="0.5,0.5" Data="M 1,1.5 L 4.5,5 8,1.5" HorizontalAlignment="Center" SnapsToDevicePixels="false" Stroke="{StaticResource DefaultT
It would be nice if the arrow was a double arrow. If not, then it should be slightly bigger than it is currently.

2019-04-12 19:43 UTC, t-eliks commented on ToNote/Views/NoteView.xaml
> +                    <TextBlock Text="Tags" FontSize="12" Foreground="{StaticResource DefaultTextBlockBrush}"/>
One last nitpick, font size could be slightly bigger, maybe 16?

2019-04-15 06:41 UTC, Hofkee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Change Tags expander button](https://trello.com/c/dpfP6aEC/65-change-tags-expander-button)

2019-04-15 16:58 UTC, t-eliks approved these changes

2019-04-15 18:48 UTC, merged

2019-04-15 18:49 UTC, Hofkee commented
![](https://github.trello.services/images/mini-trello-icon.png) [Make tags expander and autosave textblock in same line](https://trello.com/c/sA36qJFL/69-make-tags-expander-and-autosave-textblock-in-same-line)