Add ability to group notes by tags
Kodnot/ToNote pull request #46
Opened 2019-04-17 17:27 UTC by t-eliks

2019-04-17 17:27 UTC, t-eliks commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add grouping for notes](https://trello.com/c/AOIvNfOa/30-add-grouping-for-notes)

2019-04-22 11:04 UTC, Kodnot requested changes

2019-04-22 11:04 UTC, Kodnot commented on ToNote/ViewModels/MainViewModel.cs
> +        public IEnumerable AllTags { get => Notes.SelectMany(x => x.Tags).Distinct(); }
Could be written as `public IEnumerable AllTags => Notes.SelectMany(x => x.Tags).Distinct();`

2019-04-22 11:04 UTC, Kodnot commented on ToNote/ViewModels/MainViewModel.cs
> +        public ICollectionView FilteredNotes
`public ICollectionView FilteredNotes => CollectionViewSource.GetDefaultView(Notes);`

2019-04-22 11:04 UTC, Kodnot commented on ToNote/Views/MainView.xaml
> +                <StackPanel DockPanel.Dock="Top" Orientation="Horizontal">
Maybe add a margin, the dropdown list is too close to the left border of the app, it looks a bit ugly

2019-04-22 11:04 UTC, Kodnot commented on ToNote/Views/MainView.xaml
> +                    <Popup IsOpen="{Binding IsGroupingPanelOpen, Mode=TwoWay}" StaysOpen="False">
This approach feels a bit hacky to me. Why didn't you use a ComboBox or something? What's the reasoning behind implementing the dropdown via a popup?

2019-04-22 11:07 UTC, Kodnot commented
You broke dragging notes around, the program now crashes on drag. When you fix it, check if it would be possible to unit test the issue, as this part of our code breaks often and it would be nice to have some tests to prevent more regressions.

2019-04-25 18:11 UTC, Kodnot commented on ToNote/Views/MainView.xaml
> +                    <Popup IsOpen="{Binding IsGroupingPanelOpen, Mode=TwoWay}" StaysOpen="False">
The reasoning was provided on slack, this is more flexible. Still feels a bit hacky to me, the implementation could be smoother, but it'll do.

2019-04-26 18:43 UTC, t-eliks commented on ToNote/Views/MainView.xaml
> +                <StackPanel DockPanel.Dock="Top" Orientation="Horizontal">
Wasn't concerned with the look part of it, left it up for whoever styles it to come up with the best placement for it

2019-04-29 09:52 UTC, Kodnot approved these changes
Some minor changes would be nice, but otherwise great job

2019-04-29 09:52 UTC, Kodnot commented on ToNote/ViewModels/MainViewModel.cs
> +                    if (SelectedTags.Any())
You don't need this check. col.All(pred) will return true for an empty collection, so you can leave just `FilteredNotes.Filter = x => SelectedTags.All(t => ((Note)x).Tags.Contains(t));` 
There shouldn't be any performance concerns, so no reason not to prefer a more concise version.

2019-04-29 09:52 UTC, Kodnot commented on ToNoteTests/Core/VisualTreeService.cs
> +                    {
Why the double {}?

2019-04-29 10:01 UTC, merged