Added a button to remove a tag.
Kodnot/ToNote pull request #48
Opened 2019-04-28 12:06 UTC by CasuaIAz

Type tag name and click the remove button to delete the tag.

2019-04-28 21:24 UTC, t-eliks commented
Having to manually type the tag in order to delete it is terrible UX. Why not atleast make it so when you click on a tag, it gets selected and then you can press the remove button to remove it?

2019-05-13 20:33 UTC, Kodnot commented
Merge with newest dev branch and fix interactions with filtering:
- When a tag is removed, tag list for Select tags is not updated. It's only updated when a new tag is added, or the program is reloaded.
- If the user filters by tag and then removes that tag, the list of notes is not updated (eg. note A has a tag "dik", user filters by "dik", removes "dik" tag from note A, note is still shown. The list is is only refreshed after a tag is checked/unchecked).

2019-05-13 20:42 UTC, Kodnot requested changes

2019-05-13 20:42 UTC, Kodnot commented on ToNote/Views/NoteView.xaml
>                                      <TextBlock Text="{Binding}" Style="{StaticResource TagTextBlockStyle}">
`<TextBlock Text="{Binding}" Style="{StaticResource TagTextBlockStyle}" />`

2019-05-13 20:42 UTC, Kodnot commented on ToNote/Views/NoteView.xaml.cs
> +            var tagName = ((Button)sender).DataContext.ToString();
All of this breaks MVC. This should be done with commands, like adding tags and everything else. Consult @t-eliks on how to if you get stuck.

2019-05-14 11:13 UTC, Kodnot commented
![](https://github.trello.services/images/mini-trello-icon.png) [Allow user to remove tags](https://trello.com/c/KhwxGEDW/71-allow-user-to-remove-tags)

2019-05-14 19:39 UTC, closed without merging