Feat/todo tab
Kodnot/ToNote pull request #51
Opened 2019-05-11 20:49 UTC by EdotJ

Everything you need is in my commit messages, you can even see the pain I got from making this useless feature and spending too much time on it. Rape me @Kodnot @t-eliks

2019-05-11 20:49 UTC, EdotJ commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add filtering/ordering for TODOs](https://trello.com/c/EXNleNuk/25-add-filtering-ordering-for-todos)

2019-05-11 20:50 UTC, EdotJ commented
![](https://github.trello.services/images/mini-trello-icon.png) [Create a separate tab for TODOs](https://trello.com/c/OnScebl2/24-create-a-separate-tab-for-todos)

2019-05-13 20:53 UTC, Kodnot commented
Not sure how I feel about reordering todos in the todo tab. As it is now, the user seemingly can reorder only some of the tags, this leads to a confucing experience. Maybe either:
- Disable reordering in the todo tab? Would that be simple?
- Add a faint indication of note borders? Don't like the idea, as in the future if we manage to implement the ordering by date there should be no concept of todos grouped by notes.
- Deal with this in some other way?

2019-05-13 21:14 UTC, Kodnot requested changes

2019-05-13 21:14 UTC, Kodnot commented on ToNote/Controls/NotePanel.cs
> +                    todoControl.ReadFromFile(todo.FileName);
[Nitpick] VS supports autoformatting, consider using that.

2019-05-13 21:14 UTC, Kodnot commented on ToNote/Controls/TodoControl.cs
> +            this.Loaded += (s, e) =>
How about extract this into a function instead of copy-pasting it

2019-05-13 21:14 UTC, Kodnot commented on ToNote/Controls/TodoControl.cs
> +           { PropertyChangedCallback = (s, e) =>
The degradation of formatting across these changes is a gruesome representation of a man losing all hope and descending into madness

2019-05-13 21:14 UTC, Kodnot commented on ToNote/Controls/TodoControl.cs
> +                    rtb.BackspacePressedWithAltShiftModifiers += (o, a) =>
Again, extract common logic

2019-05-13 21:14 UTC, Kodnot commented on ToNote/Converters/BoolToVisibilityConverter.cs
> +                if (visibility)
Consider ternary for conciseness

2019-05-13 21:14 UTC, Kodnot commented on ToNote/Views/MainView.xaml.cs
> +    using System.Collections;
Would be nice if you cleaned up the unused usings. Would be even nicer if you used VS autoformatters and removed unused using solution-wise, as well as formatted the code (ctrl+K, ctrl+D for document, ctrl+K,ctrl+F for selected section by default)

2019-05-14 11:03 UTC, Kodnot requested changes

2019-05-14 11:03 UTC, Kodnot commented on ToNote/Controls/NotePanel.cs
> +                       panel.dt.Interval = new TimeSpan(0, 0, 0, 0, 500);
Consider using `TimeSpan.FromMilliseconds(500)` instead

2019-05-14 11:03 UTC, Kodnot commented on ToNote/Controls/TodoControl.cs
> +            if (IsDragEnabled)
Dude.

2019-05-14 11:03 UTC, Kodnot commented on ToNote/Controls/TodoControl.cs
> +                //Looks for an ExtendedRichTextBox with an x:Name="rtb" attribute from the logical children of the generated ContentPresenter which has the DataTemplate applied to it.
You might need to add `                if (VisualTreeHelper.GetChildrenCount(this) == 0)
                    return;` here

2019-05-14 11:04 UTC, Kodnot commented
Also fix the scrollviewer, it should not be visible if the number of elements is small

2019-05-14 11:56 UTC, Kodnot approved these changes

2019-05-14 11:57 UTC, merged